# Use this only as basis for your `config.yaml`

# Replaces any text in the output to `<REDACTED>`
redact_texts: []

# Rate limit requests
rate_limit: false
rate_limit_duration: 60 # seconds
rate_limit_count: 5

# for flaresolverr variants
flare_use_cache: true
flare_cache_ttl: 86400 # 1 day
