# Replaces any text with the host's api to `<REDACTED>`
replace_host_ip: true

# Rate limit requests
rate_limit: true
rate_limit_duration: 60 # seconds
rate_limit_count: 5

# for flaresolverr variants
flare_use_cache: true
flare_cache_ttl: 86400 # 1 day
